### ISSUE TITLE
Help needed: Implementing "Sign in with Google" in .NET MAUI 

### ISSUE THREAD

**Issue by NazrinAli12** [cl2raul66/MauiPaletteCreator#1]
Hi cl2raul66,

I am currently learning .NET MAUI and trying to implement the "Sign in with Google" feature. However, I am facing some difficulties, as I need to do this without using Microsoft Azure, as per my teacher's recommendation.

Could you please guide me on how to implement this feature or share any resources or sample code that could help? I would greatly appreciate your support!

Thank you in advance for your time and help.

Best regards,
Nazrin

**Comment by cl2raul66** [comment]
es algo inusual, pues todos los que trabajamos con herramientas de Microsoft sabemos que están optimizadas para otras herramientas y recursos de Microsoft... nunca he tenido que hacer esto, pero te dare una respuesta rápida [aquí](https://claude.site/artifacts/0ff02936-6f7a-4767-a3ec-5d762bf783d6). 
Nota: me gustaría que me compartieras ese proyecto para ver como lo solucionaste, buena suerte y exito.
